name: twitterbot

on:
  schedule:
    - cron: '30 6,12,18 * * *'

jobs:
  londonmapbot-post:
    runs-on: macOS-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8
      - name: Create and post tweet
        run: python run.py
